name: Ill-AfkRegion #TODO
main: net.illusion.regionafk.RegionAfkPlugin #TODO
author: Illusion
description: 템플릿 플러그인
website: https://discord.gg/illusion-shop

version: 1.0
api-version: 1.13

commands:
  잠수:
